<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require_once(APPPATH.'third_party/stripe/init.php'); // Path to Stripe PHP library

class PaymentController extends CI_Controller {
    public function __construct() {
        parent::__construct();
        \Stripe\Stripe::setApiKey('YOUR_STRIPE_SECRET_KEY');
    }

    public function index() {
        $this->load->view('payment_form');
    }

    public function process_payment() {
        $token = $this->input->post('stripeToken'); // Token generated by Stripe.js

        try {
            $charge = \Stripe\Charge::create([
                'amount' => 1000, // Amount in cents
                'currency' => 'usd',
                'source' => $token,
                'description' => 'Example Charge',
            ]);

            // Handle successful payment
            // You can redirect to a thank you page or show a success message
        } catch (\Stripe\Exception\CardException $e) {
            // Handle card errors
        } catch (\Stripe\Exception\RateLimitException $e) {
            // Handle rate limit errors
        } catch (\Stripe\Exception\InvalidRequestException $e) {
            // Handle invalid request errors
        } catch (\Stripe\Exception\AuthenticationException $e) {
            // Handle authentication errors
        } catch (\Stripe\Exception\ApiConnectionException $e) {
            // Handle API connection errors
        } catch (\Stripe\Exception\ApiErrorException $e) {
            // Handle other API errors
        }
    }
}
